### ISSUE TITLE
Directory for test target cannot be created as there is no permission to do it

### ISSUE THREAD

**Issue by naonaonao316** [dakusui/commandunit#16]
**How to reproduce**

1. Install commandunit in the former procedure written in https://github.com/dakusui/commandunit#installation.
2. Try to run tests by _commandunit run_ command in the directory where commandunit tests are defined.
3. The following error was logged and the execution failed

`$ commandunit run
mkdir: cannot create directory '/var/lib/commandunit/Users/<user_name>/Desktop/dev/gspci-shared-resources/gspci/src/test/target': Permission denied
ERROR:(exit code:1, pipe status: 1): 
  at /app/dependencies/bud/lib/core.rc:54 (abort)
  at /app/bin/commandunit:138 (main)
  at /app/bin/commandunit:193 (main)`

**Comment by dakusui** [comment]
This turned out not to be an issue in `commandunit` but in docker for mac's.
https://qiita.com/kinshotomoya/items/7b5cb9862db34315a0f1
